// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: cursor.proto

package cursorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cursor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED
	// ID of the last reversal from the query that generated this cursor
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_cursor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_cursor_proto_rawDescGZIP(), []int{0}
}

func (x *Cursor) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_cursor_proto protoreflect.FileDescriptor

const file_cursor_proto_rawDesc = "" +
	"\n" +
	"\fcursor.proto\x12\x06cursor\"\x18\n" +
	"\x06Cursor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02idB\rZ\v../cursorpbb\x06proto3"

var (
	file_cursor_proto_rawDescOnce sync.Once
	file_cursor_proto_rawDescData []byte
)

func file_cursor_proto_rawDescGZIP() []byte {
	file_cursor_proto_rawDescOnce.Do(func() {
		file_cursor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cursor_proto_rawDesc), len(file_cursor_proto_rawDesc)))
	})
	return file_cursor_proto_rawDescData
}

var file_cursor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cursor_proto_goTypes = []any{
	(*Cursor)(nil), // 0: cursor.Cursor
}
var file_cursor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cursor_proto_init() }
func file_cursor_proto_init() {
	if File_cursor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cursor_proto_rawDesc), len(file_cursor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_proto_goTypes,
		DependencyIndexes: file_cursor_proto_depIdxs,
		MessageInfos:      file_cursor_proto_msgTypes,
	}.Build()
	File_cursor_proto = out.File
	file_cursor_proto_goTypes = nil
	file_cursor_proto_depIdxs = nil
}
